import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../utils/nav-bar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Beth Jacob Hachassidi",
  description: "Generated by m.m.m.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
